# Generated by Django 4.2.1 on 2023-06-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_collection_artwork_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.collection'),
        ),
    ]
